version: 2

builds:
  - main: ./cmd/ginprov
    binary: ginprov
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
