builds:
  - id: ginprov
    main: ./cmd/ginprov
    binary: ginprov
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
