name: CI & Release

on:
  pull_request:
    branches: [main]
  push:
    tags:
      - "v*"

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v2.2.0/install.sh \
            | sh -s -- -b "$(go env GOPATH)/bin" v2.2.0

      - name: Lint
        run: golangci-lint run

      - name: Test
        run: go test -race ./...

      - name: Build
        run: make build

  release:
    name: Release
    needs: ci
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
          CGO_ENABLED: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
